import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/tanstack-provide";
import { getAllLocations } from "@/lib/api";
import { LocationWrapper } from "@/components/location-wrapper";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locations = await getAllLocations();
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
      )}
    >
      <body
        suppressHydrationWarning
        suppressContentEditableWarning
        className="min-h-full flex flex-col"
      >
        <LocationWrapper locations={locations || []}>
          <Navbar />
          <TanstackProvider>{children}</TanstackProvider>
        </LocationWrapper>
        <Toaster />
      </body>
    </html>
  );
}
