import { LocationPickerDialog } from "@/components/location-picker-dialog";
import { OptionalUserGeolocation } from "@/components/optional-user-geolocation";
import TanstackProvider from "@/components/tanstack-provide";
import { Toaster } from "@/components/ui/sonner";
import { getAllLocations } from "@/lib/api";
import { getSessionData } from "@/lib/iron-session/session.actions";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { AuthProvider } from "@/components/auth-provider";
import { getAuthSnapshot } from "@/lib/iron-session/auth/auth.actions";
import { AutoSelectLocation } from "@/components/auto-select-location";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locations = await getAllLocations();
  const sessionData = await getSessionData();
  const hasUserSavedGeo =
    typeof sessionData?.userCurrentLatitude === "number" &&
    typeof sessionData?.userCurrentLongitude === "number";
  const authSnapshot = await getAuthSnapshot();

  console.log("Session Data in RootLayout:", sessionData);
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
      )}
    >
      <body
        suppressHydrationWarning
        suppressContentEditableWarning
        className="min-h-full flex flex-col"
      >
        <LocationPickerDialog
          locations={locations || []}
          requireSelection={locations.length > 1 && !sessionData?.locationId}
        />

        {/* <OptionalUserGeolocation hasUserSavedGeo={hasUserSavedGeo} /> */}
        <AutoSelectLocation
          shouldRun={locations.length === 1 && !sessionData?.locationId}
        />

        <Navbar
          locations={locations || []}
          defaultLocation={sessionData?.locationId ?? null}
          authSnapshot={authSnapshot}
        />
        <TanstackProvider>
          <AuthProvider>{children}</AuthProvider>
        </TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
